### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#1]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Looks pretty good! Signing up and logging in works well, I made an account. Redirects all work as expected. The auth errors render and the 'x' button works well to clear them-- please also clear the errors when switching between the forms.

**Comment by w-chun** [comment]
I fixed the clear errors problem and also fixed the home page image to adjust when browser size changes.

**Comment by anastassia-b** [comment]
Excellent. The only issue now is when creating accounts that already exist, instead of a "Username is taken" error, it hits an internal server error, which doesn't render. Adding user-model level validations would probably fix it!
