### ISSUE TITLE
PA Review: Business Index Page

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#3]
- [x] Shows a list of businesses
- [x] Click on business links to business show page 
- [ ] Can filter businesses 
- [ ] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by anastassia-b** [comment]
The functionality is working well, and you have good seed data. I can see all the restaurants and navigate to one. In terms of styling, it could be visually better if:
- [x] .business-index could use a padding-top and bottom of 30px +.

**Comment by anastassia-b** [comment]
- [x] This MVP is complete once the map is back to the right side and pushed up to heroku!
