### ISSUE TITLE
PA Review: Business Show Page

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#4]
- [x] Shows information about the business
- [x] Show reviews about the business
- [x] Has button for new review to the business
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by anastassia-b** [comment]
Good progress, I see you opened up a separate issue #5 for the bug regarding fetching the business when navigating to business pages directly. We discussed that the reviews and review form could go on the business show page.

**Comment by anastassia-b** [comment]
The content and functionality of the business show page looks good. To complete this MVP, additional styling is required.

**Comment by anastassia-b** [comment]
- [x] .business-detail-container should have 2 child containers so the information could be centered/displayed nicely. 
- [x] Add a background image or carousel (if time) to each restaurant show page. You can add background: url() to the top-shelf-grey container. 
- [x] The image may obscure the Review button. Therefore, move it down to either above or below the reviews.
- [x] Add margin (maybe 30px) to review-index-item-wrapper, and margin-left to .business-details. Also could delete padding-bottom in favor of increased padding-top (30px).

**Comment by anastassia-b** [comment]
- [x] Additionally, you can make all your external links open in new tabs. So a user can continue to stay on your site.

**Comment by anastassia-b** [comment]
- [x] React-slick has several peerDependency issues, so a good alternative is to put background image(s) into the top-shelf-grey.
