### ISSUE TITLE
PA Review: Ratings/Reviews

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#6]
- [x] Users can add reviews and ratings to businesses
- [x] Users can edit previous reviews
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by anastassia-b** [comment]
When I click to leave a review, I have to login/sign up, but then I am not redirected back to the location I came from. This is a larger bug to think about.

**Comment by anastassia-b** [comment]
There was a small bug with writing reviews. You mentioned removing reviews from the demo user could be the fix. Currently, when I write a review, it does not show up with the correct text.
