### ISSUE TITLE
PA Review: Map

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#7]
- [x] Users can view business location on map
- [x] Users can search for businesses by location
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by anastassia-b** [comment]
The map is great, and has the correct markers for restaurants. However, the map does not re-center  when I search/filter by new locations. One way to handle this would be to:
- [x] Zoom out to the general SF area. OR Figure out how to recenter per search.

**Comment by anastassia-b** [comment]
Awesome, you were able to display the markers according to the search. This MVP is complete.
