### ISSUE TITLE
PA Review: Search/Filter

### ISSUE THREAD

**Issue by w-chun** [w-chun/Grubs#9]
- [x] User can search for businesses on home page
- [ ] Redirects to index page filtered by search params or no businesses found page
- [x] Search bar on the header for each page except for review form
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by anastassia-b** [comment]
Great work on getting this feature fully functional! Today you added query params to the URL to differentiate which businesses to fetch in when the component mounts. 
A few things to complete this MVP:
- [x] Add "No businesses" when there are no matches. 
- [x] Add 3 location buttons to the filter bar. For each, tie the appropriate "receive search results action".
